name: ionathon
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^8.0.3
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.5
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  animations: ^2.0.2
  particles_flutter: ^0.1.4
  flutter_spinkit: ^5.1.0
  google_fonts: ^2.2.0
  matrix4_transform: ^2.0.1
  syncfusion_flutter_charts: ^19.4.42
  liquid_progress_indicator: ^0.4.0
  provider: ^6.0.2
  get: ^4.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/searchBg.png
    - assets/iconBgNew.png
    - assets/english.png
    - assets/french.png
    - assets/math.png
    - assets/science.png
    - assets/social-science.png
    - assets/boy1Big.png
    - assets/bg.jpg

  fonts:
    - family: circe
      fonts:
        - asset: assets/fonts/circe.ttf
    - family: product
      fonts:
        - asset: assets/fonts/productsans.ttf